import { localDate } from "./portal.js";

export function createPortalDemo() {
  const after = (days) => {
    const date = new Date();
    date.setDate(date.getDate() + days);
    return localDate(date);
  };
  const time = (days, hour = 10) =>
    new Date(
      `${after(days)}T${String(hour).padStart(2, "0")}:00:00-03:00`,
    ).toISOString();
  const inst = "demo-school",
    site = "demo-site";
  return {
    institutions: [
      {
        id: inst,
        name: "Colegio Los Andes · Ejemplo",
        kind: "school",
        city: "San Juan",
        province: "San Juan",
        address: "Dirección de demostración",
        latitude: -31.5375,
        longitude: -68.5364,
        contact_name: "Responsable institucional",
        contact_email: "responsable@example.com",
        contact_phone: "",
        status: "active",
        notes: "Datos ficticios para explorar el portal.",
        archived_at: null,
      },
      {
        id: "demo-company",
        name: "Empresa Cuyo · Ejemplo",
        kind: "company",
        city: "San Juan",
        status: "active",
        archived_at: null,
      },
    ],
    memberships: [
      {
        id: "demo-member",
        institution_id: inst,
        email: "responsable@example.com",
        role: "manager",
        active: true,
      },
    ],
    sites: [
      {
        id: site,
        institution_id: inst,
        name: "Sede principal",
        address: "Dirección de demostración",
        city: "San Juan",
        notes: "",
        archived_at: null,
      },
    ],
    assets: [
      {
        id: "demo-dea",
        institution_id: inst,
        site_id: site,
        name: "DEA de recepción",
        kind: "dea",
        location: "Hall de entrada",
        manufacturer: "Equipo de ejemplo",
        model: "Modelo de práctica",
        serial_number: "DEMO-001",
        status: "attention",
        next_review_on: after(8),
        battery_expires_on: after(120),
        pads_expires_on: after(20),
        notes: "Revisar el vencimiento de electrodos.",
        archived_at: null,
      },
      {
        id: "demo-kit",
        institution_id: inst,
        site_id: site,
        name: "Botiquín del patio",
        kind: "kit",
        location: "Sala de profesores",
        status: "unknown",
        next_review_on: after(-4),
        notes: "Controlar inventario y reponer insumos.",
        archived_at: null,
      },
      {
        id: "demo-exit",
        institution_id: inst,
        site_id: site,
        name: "Salida del sector aulas",
        kind: "exit",
        location: "Pasillo norte",
        status: "operational",
        next_review_on: after(90),
        notes: "",
        archived_at: null,
      },
    ],
    activities: [
      {
        id: "demo-training",
        institution_id: inst,
        site_id: site,
        title: "RCP y uso del DEA para docentes",
        kind: "training",
        starts_at: time(12),
        ends_at: time(12, 13),
        status: "confirmed",
        responsible: "Equipo GRCP",
        location: "Salón principal",
        notes: "Práctica con maniquíes y DEA de entrenamiento.",
        report: "",
        repeat_months: 12,
        archived_at: null,
      },
      {
        id: "demo-inspection",
        institution_id: inst,
        asset_id: "demo-dea",
        title: "Revisión del DEA de recepción",
        kind: "inspection",
        starts_at: time(8),
        status: "planned",
        responsible: "Equipo GRCP",
        repeat_months: 3,
        archived_at: null,
      },
      {
        id: "demo-drill",
        institution_id: inst,
        title: "Simulacro de evacuación",
        kind: "drill",
        starts_at: time(25, 9),
        status: "planned",
        responsible: "Responsable de sede",
        repeat_months: 6,
        archived_at: null,
      },
      {
        id: "demo-old-training",
        institution_id: inst,
        title: "Primeros auxilios · Jornada inicial",
        kind: "training",
        starts_at: time(-30),
        status: "completed",
        responsible: "Equipo GRCP",
        repeat_months: 0,
        archived_at: null,
      },
    ],
    inspections: [
      {
        id: "demo-review",
        institution_id: inst,
        asset_id: "demo-exit",
        checked_on: after(-5),
        next_review_on: after(90),
        result: "pass",
        checked_by: "Equipo GRCP",
        notes: "Recorrido despejado y señalización visible.",
        checklist: [
          { text: "Recorrido despejado", ok: true },
          { text: "Señalización visible", ok: true },
        ],
      },
    ],
    participants: [
      {
        id: "demo-person",
        institution_id: inst,
        activity_id: "demo-old-training",
        full_name: "Participante de ejemplo",
        email: "participante@example.com",
        attendance: "attended",
      },
    ],
    documents: [
      {
        id: "demo-cert",
        institution_id: inst,
        activity_id: "demo-old-training",
        participant_id: "demo-person",
        title: "Certificado · Primeros auxilios",
        kind: "certificate",
        file_name: "certificado-ejemplo.pdf",
        issued_on: after(-30),
        version: 1,
        archived_at: null,
      },
    ],
    requests: [
      {
        id: "demo-request",
        institution_id: inst,
        title: "Coordinar reposición del botiquín",
        kind: "inspection",
        body: "Solicitamos revisar los insumos antes de la próxima actividad.",
        status: "open",
        response: "",
        created_at: time(-2),
      },
    ],
    audit: [],
  };
}
